name: Build

on:
  push:
    paths:
      - 'ui/**'

defaults:
  run:
    working-directory: ./ui

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'
          cache: npm

      - name: npm install
        run: npm i

      - name: npm build
        run: npm run build
