name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        working-directory: './ui'
        run: npm run pages:build
      - name: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: ui
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy
